### ISSUE TITLE
vaadin-router does not handle anchors with query params

### ISSUE THREAD

**Issue by LarsDenBakker** [vaadin/vaadin-router#249] opened 2018-08-03 22:28 UTC
https://github.com/vaadin/vaadin-router/blob/master/src/triggers/click.js#L85 uses anchor.pathname to navigate page changes, which doesn't include query parameters in the URL causing the query params to not be picked up on change.

**Comment by vlukashov** [comment] 2018-08-17 11:29
duplicate of #56

**Closed by vlukashov** 2018-08-17 11:29 UTC
