### ISSUE TITLE
Only root route seems to work for me.

### ISSUE THREAD

**Issue by chisholmd** [vaadin/vaadin-router#436] opened 2020-02-18 22:36 UTC
router.setRoutes([
			{path: '/', component: 'test-pageone'},
			{path: '/pageone', component: 'test-pageone'},
			{path: '/pagetwo', component: 'test-pagetwo'},
			{path: '(.*)', component: 'test-pagethree'}
			]);

http://localhost:5000/  <= loads pageone component
http://localhost:5000/pageone <=404
http://localhost:5000/pagetwo <=404
http://localhost:5000/somethingforwildcar <=404

Is my notation wrong?  I have switched up the routes, basically any component set to load for root works. So the problem is not the components.

**Comment by platosha** [comment] 2020-02-19 13:57
The notation seems to be correct. Unfortunately, I cannot reproduce this issue in a test.

Vaadin Router should throw a "Page not found" error in console instead of showing any 404 pages when a route is not found.

If you see a 404 page, I guess this is because of your development server. Please make sure it responds your application’s `index.html` on every request to be handled with client-side router, including `/`, `/pageone`, `/pagetwo`, `/somethingforwildcard` and so on. Often that is done with a wildcard route on the server, for example, with Express: https://gist.github.com/ryanoglesby08/1e1f49d87ae8ab2cabf45623fc36a7fe

**Comment by chisholmd** [comment] 2020-02-19 19:18
well ya...that makes a lot of sense...I was wondering what magic was being deployed that it was routing without hashes....  :)   I will check that example but one would think that the ever popular npm "serve" would handle this

**Comment by chisholmd** [comment] 2020-02-19 19:33
Yup that did it.  I used this one https://github.com/lukejacksonn/servor#readme

....but...now if I want to route without hashes I have to be able to configure S3 static hosting the same way...ugh

**Comment by chisholmd** [comment] 2020-02-19 19:33
What does one call this... hashless routing?

**Comment by chisholmd** [comment] 2020-02-20 05:07
https://medium.com/@P_Lessing/single-page-apps-on-aws-part-1-hosting-a-website-on-s3-3c9871f126

This article seems to address this, just completing this thread for others.

**Comment by platosha** [comment] 2020-02-27 13:50
Thanks for the links. Let me close the issue, as configuring web servers is not in scope of this project.

**Closed by platosha** 2020-02-27 13:50 UTC
