### ISSUE TITLE
query string params

### ISSUE THREAD

**Issue by sergicontre** [vaadin/vaadin-router#308] opened 2018-11-12 13:57 UTC
Hi, you have planned in the roadmap when the feature will be available to collect the parameters through the query string?

Thanks!

**Comment by Artur-** [comment] 2018-11-13 14:20
Same as #56

**Comment by abdonrd** [comment] 2019-07-31 09:25
Close in favor of #56? 😄

**Comment by vlukashov** [comment] 2019-08-11 20:09
Closing as a duplicate of #56.

**Closed** 2019-08-11 20:08 UTC
Labels: duplicate
