### ISSUE TITLE
Nested routes are not working properly

### ISSUE THREAD

**Issue by yaron14** [vaadin/vaadin-router#458] opened 2020-05-06 09:23 UTC
I'm trying to implement a nested routes but I found that the children component always rendered on the bottom of it's parent component.
This creates a major issue in markup and break the page if in cases there's a need to insert the child component in a specific position in the DOM.

**Comment by vlukashov** [comment] 2020-05-14 11:15
Vaadin Router relies on Shadow DOM and `<slot>`s to control the exact placing of nested children components inside a parent. See the [Nested Components](https://vaadin.github.io/vaadin-router/vaadin-router/demo/#vaadin-router-getting-started-demos) section of the Vaadin Router docs for more details.

Example: https://stackblitz.com/edit/vaadin-router-with-nested-routes?file=views/main-layout.js

So, this is by design that Vaadin Router inserts the nested route components to the bottom of the parent's light DOM. The assumption used by Vaadin Router is that any parent content would be placed into the Shadow DOM of the parent component.

I'll close this issue as an answered question. But please feel free to continue the discussion in the comments if you have further questions.

**Closed by vlukashov** 2020-05-14 11:15 UTC
Labels: ccdm
