### ISSUE TITLE
Allow lifecycle callbacks after dynamic import

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-router#320] opened 2019-02-13 13:01 UTC
It seems that the lifecycle callbacks don’t work if the component is imported with the dynamic `import()` in the `action` function as here:

https://vaadin.github.io/vaadin-router/vaadin-router/demo/#vaadin-router-code-splitting-demos

I could see that it only happens the first time. Then, once the component has already been imported dynamically, the next times… the lifecycle callbacks works

**Comment by vlukashov** [comment] 2019-02-13 21:07
Thanks for reporting an issue! A similar one has already been fixed: https://github.com/vaadin/vaadin-router/issues/271, which makes this report very interesting. Would it be possible for you to create a minimal reproducible example where the issue happens?

There is a basic example that you can use as a starting point: https://glitch.com/edit/#!/vaadin-router

**Comment by abdonrd** [comment] 2019-02-13 23:30
@vlukashov sure! Check this: https://glitch.com/edit/#!/flash-snowman

1. Open [flash-snowman.glitch.me](https://flash-snowman.glitch.me). You can see that the `home-view.js` is imported, but the `onAfterEnter()` function does not run.
2. Click on the `404 page` link.
3. Click on the `go Home` link. Now the `onAfterEnter()` function run!

**Comment by lpellegr** [comment] 2019-02-14 08:14
This issues looks like a duplicate of #282.

**Comment by moderndeveloperllc** [comment] 2019-02-20 18:18
Oof. I spent the last hour or so trying to figure out this. I have an `onBeforeEnter` that's supposed to be checking logins and it's not firing. I'm guessing this is the issue I'm having too, though I can't ever get mine to fire. I'll put up a glich if the fix here doesn't get my case too, or would you like a second one now @web-padawan?

**Comment by moderndeveloperllc** [comment] 2019-03-04 23:52
@vlukashov, @web-padawan Any thoughts on this? It makes dynamic imports pretty much worthless and therefore makes using bundlers like Webpack much harder.

**Comment by piotrekwitkowski** [comment] 2019-03-17 00:03
_Ugly_ workaround:

Step 1: expose router to imported component's module:
```js
const router = new Router(host);
router.setRoutes([
  {
    path: '/some-path', component: 'x-component', action: () => {
      import('./x-component.js').then(m => m.setRouter(router));
    },
  },
]);
```

Step 2: direct in imported module
```js
export const setRouter = r => {
  router = r;
  console.log('router saved!', router);
}
```

Step 3: use router inside component class
```js
router.constructor.go('/some-url-in-router-scope')
```

It works for me when there is only one router instance, I don't know how it works out in more complex routing scenarios.

**Comment by piotrekwitkowski** [comment] 2019-03-17 00:10
_Ugly_ workaround to access router on first render:

Step 1: expose router to imported component's module:
```js
const router = new Router(host);
router.setRoutes([
  {
    path: '/some-path', component: 'x-component', action: () => {
      import('./x-component.js').then(m => m.setRouter(router));
    },
  },
]);
```

Step 2: direct in imported module
```js
export const setRouter = r => {
  router = r;
  console.log('router saved!', router);
}
```

Step 3: use router inside component class
```js
router.constructor.go('/some-url-in-router-scope')
```

It works for me when there is only one router instance, I don't know how it works out in more complex routing scenarios.

**Comment by vlukashov** [comment] 2019-08-19 06:58
It looks like the root cause of this issue is that router does not handle well the case when a route web component is loaded async to the route resolution.

A workaround would be making router to wait until the route component is loaded before proceeding with the rest of the route resolution steps (including lifecycle callbacks):

```js
const router = new Router(host);
router.setRoutes([
  {
    path: '/some-path',
    component: 'x-component',
    action: async () => {
      await import('./x-component.js');
    },
  },
]);
```

**Comment by moderndeveloperllc** [comment] 2019-08-19 13:41
@vlukashov That would appear to fix the issue, at least in naive instances such as the glitch.me by @abdonrd and [me](https://colossal-ton.glitch.me/). Should this then be just a documentation issue instead of bug? Not sure if there is really a downside to the having async/await for all dynamic imports, even if there are no lifecycle methods to fire.

**Closed** 2019-08-29 08:56 UTC
Labels: bug, ccdm
