### ISSUE TITLE
Support for sending data to child routes?

### ISSUE THREAD

**Issue by aviskarkc10** [vaadin/vaadin-router#388] opened 2019-09-12 04:54 UTC
Is there a way to send data to the child routes?

Currently I am defining my routes in my `LitElement` app like this:
```js
export function init(outlet) {
  const router = new Router(outlet);

  router.setRoutes([
    {
      path: HOME,
      redirect: 'routeOne'
    },
    {
      path: '/route-one',
      component: 'route-one',
      action: () => {
        import(
          /* webpackChunkName: "route-one" */ './route-one'
        );
      },
      children: [
        {
          path: childOne
        },
        {
          path: childTwo
        }
      ]
    },
    {
      path: '/route-two',
      component: 'route-two',
      action: () => {
        import(
          /* webpackChunkName: "route-two" */ './route-two'
        );
      }
  ]);
}
```

Is there any way I can send `props` to the child components (`childOne`, `childTwo`) from the parent component (`routeOne`)?

That would be great as I could keep all my logic/data in the parent component. I really don't want to use a state management library like `redux` for this. `React` allows this by allowing passing props when defining the routes. Maybe we could allow something like that by passing an argument when defining the routes:

```js
// pass data here
export function init(outlet, data) {
  const router = new Router(outlet);

  router.setRoutes([
    {
      path: HOME,
      redirect: 'routeOne'
    },
    {
      path: '/route-one',
      component: 'route-one',
      action: () => {
        import(
          /* webpackChunkName: "route-one" */ './route-one'
        );
      },
      data: data,           // pass props here
      children: [
        {
          path: childOne
        },
        {
          path: childTwo
        }
      ]
    },
    {
      path: '/route-two',
      component: 'route-two',
      action: () => {
        import(
          /* webpackChunkName: "route-two" */ './route-two'
        );
      },
     data: { name: data.name }            // pass data here
  ]);
}
```

**Comment by vlukashov** [comment] 2021-01-05 10:24
looks like a duplicate of https://github.com/vaadin/vaadin-router/issues/444

**Closed by vlukashov** 2021-01-05 10:24 UTC
