### ISSUE TITLE
When navigation is prevented, URI path should not change

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-router#352] opened 2019-08-16 06:54 UTC
Preventing navigation in router works as it does keep the previous context, but the behavior is  different when trying to navigate through page links or history buttons, in the first case the URI is kept and aligned with the active view, but in the case of back/forward buttons URI and view are not aligned.

The screen-shot attached for the code in the snippet demonstrates the issue

```js
import { Router } from '@vaadin/router';

const routes = [
    {
        path: '(.*)',
        action: async (cfg) => {
            const elm = document.createElement('div');
            elm.textContent = 'Hi ' + cfg.pathname;
            elm.onBeforeEnter = function(ctx, args) {
                return window.preventNavigation && args.prevent();
            }
            return elm;
        }
    }
];

const router = new Router(document.querySelector('#outlet'), {});
router.setRoutes(routes);
```

![router-preventNavigation](https://user-images.githubusercontent.com/161853/63149047-b7109000-c00b-11e9-918a-f815f043a031.gif)

**Comment by vlukashov** [comment] 2019-08-16 06:57
duplicate of #329

**Closed by vlukashov** 2019-08-16 06:57 UTC
Labels: ccdm
