### ISSUE TITLE
Error message for missing component of a route

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-router#431] opened 2020-02-03 10:01 UTC
I made a simple typo when adding a route:
```
const routes = [
  {
    path: '',
    component: 'main-layout',
    children: [
      {path: 'location', 
       component: 'locations-view', // typo here
       action: async () => { await import('./views/location/location-view')}},
```
I used the component name `locations-view` when I should have used `location-view`. When navigating to this route, nothing is shown (because there is no such component). For a first-timer's DX, it would be helpful if there was an error message saying something like "component 'locations-view' not found". Understandably this is not trivial, as the component may be added lazily, but IMO worth investigating regardless.

**Comment by vlukashov** [comment] 2020-02-04 12:18
Still a valid issue. Duplicate of #172

**Closed by vlukashov** 2020-02-04 12:18 UTC
