### ISSUE TITLE
Shut off router

### ISSUE THREAD

**Issue by jonmann20** [vaadin/vaadin-router#472] opened 2020-08-07 15:11 UTC
Is there a way to shut off the router?

e.g.
```js
const router = new Router(outlet);
router.setRoutes();

// a few moments later

router.stop();
```

I've tried `.unsubscribe()`, but I still get path not found errors.

**Comment by haijian-vaadin** [comment] 2020-08-07 18:21
Hi @jonmann20, what's your use case of shutting off router? Not sure if this can help, to make a link not managed by router, you can use the `router-ignore` attribute, e.g. `<a href="xxx" router-ignore>XXX</a>`.

**Comment by jonmann20** [comment] 2020-08-07 18:29
Hello, thanks for the quick response.  I am writing an abstract login component that changes the URL, but I need to give control of routing back to the application once login is successful.

In this case ignoring links won't work as I need a different clientside router in place.

**Comment by vlukashov** [comment] 2020-08-11 10:53
> I've tried `.unsubscribe()`, but I still get path not found errors.

The `unsubscribe()` method should do exactly what you describe here. If it does not, it sounds like a bug. Could you please create a small example showing the issue?

[You could use an online IDE like [StackBlitz](https://stackblitz.com/edit/vaadin-router-with-nested-routes?file=index.html) or [Glitch](https://glitch.com/edit/#!/highlight-current-nav-link?path=index.js%3A1%3A0) and start by forking an example Vaadin Router project]

**Comment by jonmann20** [comment] 2020-08-14 15:54
So I'm not sure this is actually an issue.  In my original code I was also using removeRoutes() and a service worker (via es-dev-server) was still serving the old files making it look like the router was still active.

Here is a glitch to show what is happening.  With the `removeRoutes()` preceding `unsubscribe()` an error is thrown.

```
[Vaadin.Router] Page not found (/demo.html)
```

https://glaze-water-bread.glitch.me/demo.html

https://glitch.com/~glaze-water-bread   (home-view.js#L22)

**Comment by haijian-vaadin** [comment] 2020-08-25 10:47
I will close this ticket for now, we can reopen it later on if the problem is confirmed from the router.

**Closed by haijian-vaadin** 2020-08-25 10:47 UTC
Labels: ccdm
