### ISSUE TITLE
Randomly dies on Safari / iOS (mojave) after several navigation steps...

### ISSUE THREAD

**Issue by pitus** [vaadin/vaadin-router#330] opened 2019-03-20 17:19 UTC
I'm not sure why, but Yesterday the Browser Support showed Red (failing) on iPhone, Safari, and Chrome 73 but Today it's all Green ?

I've been struggling for days now trying to figure out why my PWA just stops responding to navigation after several clicks - it no longer instantiates my custom control within the outlet and once it's in that state, the only way to get the content showing again is to reload the page.
I even added a timer code that toggles between two very simple pages and it keeps on dying on iOS after random number of clicks, sometimes less than 10 is enough, other times even 60-100 until it breaks.
Also, when I have the Web Inspector active, the problem doesn't happen - it can go forever, properly refreshing each page.
Another thing - if I run my timer with 250ms interval (very fast switching) then it also works fine until reaching 100 history pushes, at which point Safari prevents further navigation for a while...
So, this looks like some kind of a timing or resource issue, it's completely unpredictable.

How can I submit a sample code that will demonstrate this? It has an index.html page, one app component with the router in it & two simple routes and two other components to be instantiated in the outlet - they use lit-element but are very simple, just a render with simple text.

**Comment by pitus** [comment] 2019-03-21 00:56
I just tried the same test with the latest vaadin-router 1.2 and latest Lit-Element and it's much more stable on Safari 12.0 (14606.1.17.40.4) - actually, keeps running (flipping between two pages) indefinitely or until I launch Web Inspector, Console View ... as soon as Inspector comes up, the page dies and no longer refreshes the content, but keeps on going, showing updates outside of the 'outlet' element.
Same when I close the Inspector, it dies immediately... and requires a refresh of the page, then it keeps on going so something's been improved.

**Comment by pitus** [comment] 2019-03-21 02:35
Well ... turns out this is more frustrating than I thought.
After an update, it behaved correctly for a long time, but within the real application it died and continues dying as with the previous version ... What's strange is that I can no longer crash the older version no matter what I do - so this is completely unpredictable (not sure if the problem is with some event interaction between vaadin-router and Safari or something in Safari / iOS that's not fully supporting Shadow Dom ... giving up on it, unless someone from vaadin has an idea how to address this issue? If not, I'll have to find another router and hope it'll be more stable :(

**Comment by web-padawan** [comment] 2019-03-21 07:03
Thanks for the issue. Have you tested on Safari 12.0 only? Would be nice to also test in different version, at least 11 to see how it works there, to ensure if that's the regression in Safari. 

Hard to say what the reason could be, the only thing 'm aware of is that Safari 12 has [issues](https://bugs.webkit.org/show_bug.cgi?id=190756) with tagged template literals caching (which is something you might face with LitElement) and that should be addressed in Babel 7.4.0. It might be related to the problem, but that's just my guess.

**Comment by pitus** [comment] 2019-03-22 01:06
I don't have any other Safari version available, in fact, I don't have a Mac - had to find a way to test this virtually and it was a pain to narrow down the problem.

I just changed the code to use my own router & component-switching instead of using vaadin-router and everything works just fine, no mode disappearing content no matter how many times the page changes and is updated so it doesn't appear that Safari has problems with Lit-Element after all.

I can send you a set of test files that demonstrate the problem if that can help you fix it - I'm actually surprised that nobody has reported this so far, are people actually using it on iOS ?

**Comment by pitus** [comment] 2019-03-22 01:10
I will probably try using just the Resolver and see if it works. Perhaps the problem is with the way vaadin-router instantiates components? My current version uses a custom component that, based on the route, renders an html with one of the chosen other components - yes, it's a primitive way of handling what component is responsible for the content based on the URL, but so far it works and it instantiates component via lit-html.

**Comment by pitus** [comment] 2019-03-26 23:56
OK, I've managed to use Resolver + pwa-helper/installRouter.js with some modifications so that I can call Router.go() and stay compatible with the vaadin-router to a point... until vaadin-router gets fixed to properly work with iOS/Safari.
As a hint, I think the problem is with some timing. From my observations, every time it died, there was a short glitch in refresh and/or something else took longer than expected and something in vaadin-router didn't get executed on time? I don't have the time to investigate this any further.

**Comment by web-padawan** [comment] 2019-06-02 18:53
Closing as we don't have enough information on what exactly should be fixed. As I mentioned above, it might be a Safari 12 issue and not necessarily related to Router.

If someone provides a reproduction, let's reopen this issue and investigate it further.

**Closed by web-padawan** 2019-06-02 18:53 UTC
